### PR TITLE
#10 http exception compile fix

### LINKED ISSUE #11: Two instances of the same class in HTTPException

### PR DESCRIPTION
**Pull request by robertrinh**
issue fix #11 
also fixed the compilation errors

### CODE REVIEW

File: src/response/HTTPStatusLine.cpp [hunk 1]
```diff
@@ -21,12 +21,19 @@ const std::string HTTPStatusLine::m_protocol = PROTOCOL;
 HTTPStatusLine::HTTPStatusLine(HTTPStatusCode status_code)
     : m_status_text {get_http_status_text(status_code)}
     , m_status_code {status_code}
+{}
+
+HTTPStatusLine& HTTPStatusLine::operator=(const HTTPStatusLine& other)
 {
-    
+    const_cast<std::string&>(m_status_text) = other.m_status_text;
```
Comment (rutgermeuzelaar) [inline src/response/HTTPStatusLine.cpp:28]: Might be better to make these properties non-const so we don't have to use const_cast here.

**Review by rutgermeuzelaar — APPROVED** [review]
